DIR=${PWD}
PROBLEM=$(notdir ${DIR})
CPPVersions=gardener_sjz gardener_bcs
JAVAVersions=Gardener_zeil
Tests=test0 grid sortOfSpiral twoRooms minimal small pinwheel slivers serpentine test1 gardener_bcs cube points750
#
#
include ../make.problem
